apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: abspr1pta-java-quarkus
  janus-idp.io/tekton: abspr1pta-java-quarkus
  backstage.io/kubernetes-id: abspr1pta-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: abspr1pta-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
